CREATE CATALOG IF NOT EXISTS fmcg;

USE CATALOG fmcg;

CREATE SCHEMA IF NOT EXISTS s3_sportsbar;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
